### ISSUE TITLE
Gruntfile.js should be corrected to run on Mac in Mono environment

### ISSUE THREAD

**Issue by AndrewSaninCreuna** [whyleee/generator-aspnet-powermvc#1]
- line 276: remove browser identification `app: 'chrome'` - default browser will be used
- line 81: `maxCpuCount: 8` is not supported by mono xbuild. Leads to a warning that block build operation

**Comment by whyleee** [comment]
Chrome line is removed. Entire `msbuild` task is removed, because it causes to many problems in different projects. If somebody needs it - he will install it and configure himself. So the second issue if fixed too :wink:.

Fix will be released in the next version. You can clone beta version from `vnext` branch, that already contains this fix.
